#!/bin/bash
# -*- mode: shell-script; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
# ex: ts=8 sw=4 sts=4 et filetype=sh

[[ $1 = '-h' ]] && {
    [ -x "/usr/sbin/load_policy" -o -x "/sbin/load_policy" ] || exit 1
    exit 0
}

exit 0

