#!/bin/bash

dd if=/dev/zero of=test/root.ext2 bs=1M count=20
mke2fs -F test/root.ext2
mkdir test/mnt
mount -o loop test/root.ext2 test/mnt

initdir=test/mnt
kernel=$(uname -r)
(
    . ./dracut-functions
    dracut_install sh df free ls shutdown poweroff stty cat ps ln ip route \
	/lib/terminfo/l/linux mount dmesg ifconfig dhclient mkdir cp ping dhclient 
    inst "modules.d/40network/dhclient-script" "/sbin/dhclient-script"
    inst "modules.d/40network/ifup" "/sbin/ifup"
    dracut_install grep
    inst test/test-init /sbin/init
    find_binary plymouth >/dev/null && dracut_install plymouth
    (cd "$initdir"; mkdir -p dev sys proc etc var/run tmp )
)
targetfs="$initdir"
unset initdir


umount test/mnt
rm -fr test/mnt
