#!/bin/sh
exec >/dev/console 2>&1
export TERM=linux
ln -s /proc/mounts /etc/mtab
export PS1='initramfs-test:\w\$'
stty sane
echo "made it to the rootfs!"
echo 3 >/proc/sys/vm/drop_caches
free
sh -i
mount -o remount,ro /
poweroff -f