#!/bin/sh
# -*- mode: shell-script; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
# ex: ts=8 sw=4 sts=4 et filetype=sh
type -P biosdevname >/dev/null || exit 1

# do not enable bootchartd by default
exit 0
