# Add 'branches' label to any pull request
branches:
- "*"

# Add 'rhel-8' branch label to any pull request
rhel-8:
- "*"

# Add 'needs review' label to any pull request
needs review:
- "*"

# Add 'repository' label to any root file changes
repository:
- ./*

# Add 'github' label to any .github/ file changes
github:
- .github/*
- .github/**/*

# Add 'mkosi' label to any .mkosi/ file changes
mkosi:
- .mkosi/*
- .mkosi/**/*
- .mkosi/**/**/*

# Add 'dracut install' label to any install/  file changes
dracut install:
- install/*
- install/**/*

# Add 'example' label to any examples/ file changes
example:
- examples/*
- examples/**/*
- examples/**/**/*

# Add a 'modules' label to any modules.d/ file changes
modules:
- modules.d/*
- modules.d/**/*

# Add a 'bash' label to any bash module changes
- modules.d/00bash/*

# Add a 'bootchart' label to any bootchart module changes
- modules.d/00bootchart/*

# Add a 'dash' label to any dash module changes
- modules.d/00dash/*

# Add a 'mksh' label to any mksh module changes
- modules.d/00mksh/*

# Add a 'systemd' label to any systemd module changes
- modules.d/00systemd/*

# Add a 'warpclock' label to any warpclock module changes
- modules.d/00warpclock/*

# Add a 'fips' label to any fips module changes
- modules.d/01fips/*

# Add a 'systemd-initrd' label to any systemd-initrd module changes
- modules.d/01systemd-initrd/*

# Add a 'caps' label to any caps module changes
- modules.d/02caps/*

# Add a 'systemd-networkd' label to any systemd-networkd module changes
- modules.d/02systemd-networkd/*

# Add a 'modsign' label to any modsign module changes
- modules.d/03modsign/*

# Add a 'rescue' label to any rescue module changes
- modules.d/03rescue/*

# Add a 'watchdog' label to any watchdog module changes
- modules.d/04watchdog/*

# Add a 'busybox' label to any busybox module changes
- modules.d/05busybox/*

# Add a 'rngd' label to any rngd module changes
- modules.d/06rngd/*

# Add a 'i18n' label to any i18n module changes
- modules.d/10i18n/*

# Add a 'convertfs' label to any convertfs module changes
- modules.d/30convertfs/*

# Add a 'network-legacy' label to any network-legacy module changes
- modules.d/35network-legacy/*

# Add a 'network-manager' label to any network-manager module
- modules.d/35network-manager/*

# Add a 'network' label to any network module changes
- modules.d/40network/*

# Add a 'ifcfg' label to any ifcfg module changes
- modules.d/45ifcfg/*

# Add a 'url-lib' label to any url-lib module changes
- modules.d/45url-lib/*

# Add a 'drm' label to any drm module changes
- modules.d/50drm/*

# Add a 'gensplash' label to any gensplash module changes
- modules.d/50gensplash/*

# Add a 'plymouth' label to any plymouth module changes
- modules.d/50plymouth/*

# Add a 'cms' label to any cms module changes
- modules.d/80cms/*

# Add a 'lvmmerge' label to any lvmmerge module changes
- modules.d/80lvmmerge/*

# Add a 'cio_ignore' label to any cio_ignore module changes
- modules.d/81cio_ignore/*

# Add a 'btrfs' label to any btrfs module changes
- modules.d/90btrfs/*

# Add a 'crypt' label to any crypt module changes
- modules.d/90crypt/*

# Add a 'dm' label to any dm module changes
- modules.d/90dm/*

# Add a 'dmraid' label to any dmraid module changes
- modules.d/90dmraid/*

# Add a 'dmsquash-live' label to any dmsquash-live module changes
- modules.d/90dmsquash-live/*

# Add a 'dmsquash-live-ntfs' label to any dmsquash-live-ntfs changes
- modules.d/90dmsquash-live-ntfs/*

# Add a 'kernel-modules' label to any kernel-modules module changes
- modules.d/90kernel-modules/*

# Add a 'kernel-modules-extra' label to any kernel-modules-extra changes
- modules.d/90kernel-modules-extra/*

# Add a 'kernel-network-modules' label to any kernel-network-modules changes
- modules.d/90kernel-network-modules/*

# Add a 'livenet' label to any livenet module changes
- modules.d/90livenet/*

# Add a 'lvm' label to any lvm module changes
- modules.d/90lvm/*

# Add a 'mdraid' label to any mdraid module changes
- modules.d/90mdraid/*

# Add a 'multipath' label to any multipath module changes
- modules.d/90multipath/*

# Add a 'nvdimm' label to any nvdimm module changes
- modules.d/90nvdimm/*

# Add a 'ppcmac' label to any ppcmac module changes
- modules.d/90ppcmac/*

# Add a 'qemu' label to any qemu module changes
- modules.d/90qemu/*

# Add a 'qemu-net' label to any qemu-net module changes
- modules.d/90qemu-net/*

# Add a 'stratis' label to any stratis module changes
- modules.d/90stratis/*

# Add a 'crypt-gpg' label to any crypt-gpg module changes
- modules.d/91crypt-gpg/*

# Add a 'crypt-loop' label to any crypt-loop module changes
- modules.d/91crypt-loop/*

# Add a 'zipl' label to any zipl module changes
- modules.d/91zipl/*

# Add a 'cifs' label to any cifs module changes
- modules.d/95cifs/*

# Add a 'dasd' label to any dasd module changes
- modules.d/95dasd/*

# Add a 'dasd_mod' label to any dasd_mod module changes
- modules.d/95dasd_mod/*

# Add a 'dasd_rules' label to any dasd_rules module changes
- modules.d/95dasd_rules/*

# Add a 'dcssblk' label to any dcssblk module changes
- modules.d/95dcssblk/*

# Add a 'debug' label to any debug module changes
- modules.d/95debug/*

# Add a 'fcoe' label to any fcoe module changes
- modules.d/95fcoe/*

# Add a 'fcoe-uefi' label to any fcoe-uefi module changes
- modules.d/95fcoe-uefi/*

# Add a 'fstab-sys' label to any fstab-sys module changes
- modules.d/95fstab-sys/*

# Add a 'iscsi' label to any iscsi module changes
- modules.d/95iscsi/*

# Add a 'lunmask' label to any lunmask module changes
- modules.d/95lunmask/*

# Add a 'nbd' label to any nbd module changes
- modules.d/95nbd/*

# Add a 'nfs' label to any nfs module changes
- modules.d/95nfs/*

# Add a 'nvmf' label to any nvmf module changes
- modules.d/95nvmf/*

# Add a 'qeth_rules' label to any qeth_rules module changes
- modules.d/95qeth_rules/*

# Add a 'resume' label to any resume module changes
- modules.d/95resume/*

# Add a 'rootfs-block' label to any rootfs-block module changes
- modules.d/95rootfs-block/*

# Add a 'ssh-client' label to any ssh-client module changes
- modules.d/95ssh-client/*

# Add a 'terminfo' label to any terminfo module changes
- modules.d/95terminfo/*

# Add a 'udev-rules' label to any udev-rules module changes
- modules.d/95udev-rules/*

# Add a 'virtfs' label to any virtfs module changes
- modules.d/95virtfs/*

# Add a 'zfcp' label to any zfcp module changes
- modules.d/95zfcp/*

# Add a 'zfcp_rules' label to any zfcp_rules module changes
- modules.d/95zfcp_rules/*

# Add a 'znet' label to any znet module changes
- modules.d/95znet/*

# Add a 'securityfs' label to any securityfs module changes
- modules.d/96securityfs/*

# Add a 'biosdevname' label to any biosdevname module changes
- modules.d/97biosdevname/*

# Add a 'masterkey' label to any masterkey module changes
- modules.d/97masterkey/*

# Add a 'dracut-systemd' label to any dracut-systemd module changes
- modules.d/98dracut-systemd/*

# Add a 'ecryptfs' label to any ecryptfs module changes
- modules.d/98ecryptfs/*

# Add a 'integrity' label to any integrity module changes
- modules.d/98integrity/*

# Add a 'pollcdrom' label to any pollcdrom module changes
- modules.d/98pollcdrom/*

# Add a 'selinux' label to any selinux module changes
- modules.d/98selinux/*

# Add a 'syslog' label to any syslog module changes
- modules.d/98syslog/*

# Add a 'usrmount' label to any usrmount module changes
- modules.d/98usrmount/*

# Add a 'base' label to any base module changes
- modules.d/99base/*

# Add a 'fs-lib' label to any fs-lib module changes
- modules.d/99fs-lib/*

# Add a 'img-lib' label to any img-lib module changes
- modules.d/99img-lib/*

# Add a 'memstrack' label to any memstrack module changes
- modules.d/99memstrack/*

# Add a 'shutdown' label to any shutdown module changes
- modules.d/99shutdown/*

# Add a 'squash' label to any squash module changes
- modules.d/99squash/*

# Add a 'uefi-lib' label to any uefi-lib module changes
- modules.d/99uefi-lib/*

# Add 'test' label to any test/ file changes
test:
- test/*
- test/**/*

# Add 'dracut' label for anything else
dracut:
- any: ['!.github/', '!.mkosi/', '!install/', '!examples/', '!modules.d/', '.test/']
