#!/bin/bash
# -*- mode: shell-script; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
# ex: ts=8 sw=4 sts=4 et filetype=sh
inst_hook cmdline 30 "$moddir/parse-dasd.sh"
dracut_install tr dasdinfo dasdconf.sh
if [[ $hostonly ]]; then
    inst /etc/dasd.conf
fi
inst_rules 56-dasd.rules
inst_rules 59-dasd.rules
