#!/bin/bash

# install all currently loaded modules in initrd

/sbin/lsmod | while read mod rest; do
	instmods "$mod"
done

[ -f /etc/modprobe.conf ] && dracut_install /etc/modprobe.conf

for i in $(find /etc/modprobe.d/ ); do
         inst $i
done

