#!/bin/bash
dracut_install mount mknod mkdir modprobe pidof sleep chroot echo sed sh ls

# install our scripts and hooks
inst "$initfile" "/init"
inst "$switchroot" "/sbin/switch_root"
for hookdir in $hookdirs; do
    for hook in "$dsrc/$hookdir"/*; do
	[[ -f $hook ]] && inst "$hook" "/$hookdir/${hook##*/}"
    done
done

