#!/bin/sh
# -*- mode: shell-script; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
# ex: ts=8 sw=4 sts=4 et filetype=sh

# We depend on network modules being loaded
[ "$1" = "-d" ] && echo network

# FIXME
# If hostonly was requested, fail the check until we have some way of
# knowing we are booting from FCoE
[ "$1" = "-h" ] && exit 1

exit 0
