#!/bin/sh
#
# We get called like this:
# /sbin/fcoe-up <network-device> <dcb|nodcb>
#
# Note currently only nodcb is supported, the dcb option is reserved for
# future use.

PATH=$PATH:/sbin:/usr/sbin

# Huh? Missing arguments ??
[ -z "$1" -o -z "$2" ] && exit 1

export PS4="fcoe-up.$1.$$ + "
exec >>/dev/initlog.pipe 2>>/dev/initlog.pipe
. /lib/dracut-lib.sh

netif=$1
dcb=$2

/sbin/ip link set "$netif" up
wait_for_if_up "$netif"

if [ "$dcb" = "dcb" ]; then
    # Note lldpad will stay running after switchroot, the system initscripts
    # are to kill it and start a new lldpad to take over. Data is transfered
    # between the 2 using a shm segment
    lldpad -d
    # stupid tools, need sleep
    sleep 1
    dcbtool sc "$netif" dcb on
    sleep 1
    dcbtool sc "$netif" app:fcoe e:1 a:1 w:1
    sleep 1
    fipvlan "$netif" -c -s
else
    echo -n "$netif" > /sys/module/fcoe/parameters/create
fi
