#!/bin/bash

dracut_install ip dcbtool fipvlan

inst lldpad
mkdir -p "$initdir/var/lib/lldpad"

inst "$moddir/fcoe-up" "/sbin/fcoe-up"
inst_hook pre-udev 60 "$moddir/fcoe-genrules.sh"
inst_hook cmdline 99 "$moddir/parse-fcoe.sh"
