# This file is part of dracut.
# SPDX-License-Identifier: GPL-2.0-or-later

# The name of the upstream package
upstream_package_name: dracut

# The upstream tag versioning scheme
upstream_tag_template: "{version}"

# The URL of the upstream project
upstream_project_url: https://github.com/dracutdevs/dracut

# Relative path to a spec file within the upstream repository
specfile_path: pkgbuild/dracut.spec

# Name of the downstream package
downstream_package_name: dracut

# The URL of the downstream project
dist_git_base_url: https://src.fedoraproject.org/

# Sync file(s) from upstream repo to dist-git
synced_files:
  # The dracut spec file is maintained upstream so we sync it downstream.
  - dracut.spec
  # We sync the packit file downstream be able to optionally use the sync-from-downstream command
  - .packit.yaml

# We want new releases to be automatically built on rawhide and have few jobs
# on copr.
create_pr: false
jobs:
- job: propose_downstream
  trigger: release
  metadata:
    dist_git_branches: main

- job: tests
  trigger: pull_request
  metadata:
    targets:
      - fedora-rawhide

- job: copr_build
  trigger: pull_request
  metadata:
    targets:
      - fedora-development

- job: copr_build
  trigger: commit
  metadata:
    targets:
      - fedora-all
      - fedora-development
