#!/bin/bash
if [ -z "$drivers" ]; then
  drivers="sd_mod =fs"
  # Include block controller drivers
  for modname in $(find "$srcmods/kernel/drivers" -name '*.ko'); do
    if nm -uPA $modname | egrep -q 'ata_scsi_ioctl|scsi_add_host|blk_init_queue|register_mtd_blktrans|scsi_esp_register'; then
      drivers="${drivers} $modname"
    fi
  done
fi
instmods $drivers
