#!/bin/bash
# -*- mode: shell-script; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
# ex: ts=8 sw=4 sts=4 et filetype=sh

# if there's no multipath binary, no go.
type -P multipath >/dev/null || exit 1

[[ $1 = -d ]] && exit 0

. $dracutfunctions
[[ $debug ]] && set -x

is_mpath() {
    [ -e /sys/dev/block/$1/dm/uuid ] || return 1
    [[ $(cat /sys/dev/block/$1/dm/uuid) =~ ^mpath- ]] && return 0
    return 1
}

if [[ $1 = -h ]]; then
    rootdev=$(find_root_block_device)
    if [[ $rootdev ]]; then
        check_block_and_slaves is_mpath "$rootdev" && exit 0
    fi
    exit 1
fi

exit 0
