#!/bin/bash
# -*- mode: shell-script; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
# ex: ts=8 sw=4 sts=4 et filetype=sh

for f in  \
    /sbin/dmsetup \
    /sbin/kpartx \
    /sbin/mpath_wait \
    /sbin/multipath  \
    /sbin/multipathd \
    /sbin/xdrgetuid \
    /sbin/xdrgetprio \
    /etc/xdrdevices.conf \
    /etc/multipath.conf \
    /etc/multipath/wwids \
    "$libdir"/libmultipath* "$libdir"/multipath/*; do
    [ -e "$f" ] && inst "$f"
done

inst_hook pre-trigger 02 "$moddir/multipathd.sh"
inst_hook pre-pivot   02 "$moddir/multipathd-stop.sh"
inst_rules 40-multipath.rules
