#!/bin/bash

mp_mod_test() {
    local mpfuncs='scsi_register_device_handler|dm_dirty_log_type_register|dm_register_path_selector|dm_register_target'
    nm -uPA "$1" | egrep -q "$mpfuncs"
}

instmods $(filter_kernel_modules mp_mod_test)
