#!/bin/bash
dracut_install umount
inst dmsetup
inst blkid
inst dd
inst losetup

# eject might be a symlink to consolehelper
if [ -L /usr/bin/eject ]; then
    dracut_install /usr/sbin/eject
else
    inst eject
fi

inst blockdev
which checkisomd5 >/dev/null 2>&1 && inst checkisomd5
inst_hook cmdline 30 "$moddir/parse-dmsquash-live.sh"
inst_hook pre-udev 30 "$moddir/dmsquash-live-genrules.sh"
inst "$moddir/dmsquash-live-root" "/sbin/dmsquash-live-root"
# should probably just be generally included
inst_rules 60-cdrom_id.rules
