#!/bin/bash
# -*- mode: shell-script; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
# ex: ts=8 sw=4 sts=4 et filetype=sh
arch=$(uname -m)
[ "$arch" = "s390" -o "$arch" = "s390x" ] || exit 1 

exit 0
