#!/bin/bash
inst_hook cmdline 30 "$moddir/parse-zfcp.sh"
dracut_install tr

inst /sbin/zfcpconf.sh
inst_rules 56-zfcp.rules

if [[ $hostonly ]]; then
    inst /etc/zfcp.conf
fi
dracut_install zfcp_cio_free grep sed

