#!/bin/bash

# if we don't have dmraid installed on the host system, no point
# in trying to support it in the initramfs.
which dmraid >/dev/null 2>&1 || exit 1

. $dracutfunctions

is_dmraid() { /lib/udev/vol_id /dev/block/$1 |grep -v linux_raid_member | \
    grep -q _raid_member; }

[[ $1 = '-h' ]] && {
    rootdev=$(find_root_block_device)
    if [[ $rootdev ]]; then
	# root lives on a block device, so we can be more precise about 
	# hostonly checking
	check_block_and_slaves is_dmraid "$rootdev" || exit 1
    else
	# root is not on a block device, use the shotgun approach
	dmraid -r | grep -q ok || exit 1
    fi
}

exit 0
