#!/bin/bash
dracut_install dmraid partx kpartx 

inst  dmeventd
inst  /usr/lib*/libdmraid-events-isw.so
inst_rules 10-dm.rules 12-dm-disk.rules 95-dm-notify.rules 

inst "$moddir/dmraid.sh" /sbin/dmraid_scan

if [ ! -x /lib/udev/vol_id ]; then
    inst_rules 64-md-raid.rules
fi

inst_rules "$moddir/61-dmraid-imsm.rules"
inst "$moddir/dmraid-cleanup.sh" /sbin/dmraid-cleanup
inst_hook pre-trigger 30 "$moddir/parse-dm.sh"

