#!/bin/sh 
export TERM=linux
export PS1='nfstest-server:\w\$ '
stty sane
echo "made it to the rootfs!"
. /etc/basenet
echo server > /proc/sys/kernel/hostname
ip addr add 127.0.0.1/8 dev lo
ip link set lo up
ip addr add $BASENET.1/24 dev eth0
ip link set eth0 up
rpcbind
modprobe nfsd
exportfs -r
rpc.nfsd
rpc.mountd
/usr/sbin/dnsmasq
#sh -i
# Wait forever for the VM to die
while sleep 60; do sleep 60; done
mount -n -o remount,ro /
poweroff -f
