#!/bin/bash
# Include wired net drivers, excluding wireless
for modname in $(find "$srcmods/kernel/drivers" -name '*.ko'); do
  if nm -uPA $modname | egrep -q 'eth_type_trans|register_virtio_device' \
 	&& ! nm -uPA $modname | egrep -q 'iw_handler_get_spy'; then
    if echo "$modname" | egrep -q '/wireless/|/isdn/|/uwb/'; then
      continue
    else
      instmods $modname 
    fi
  fi
done
instmods ecb arc4
# bridge modules
instmods bridge stp llc
