#!/bin/bash
# -*- mode: shell-script; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
# ex: ts=8 sw=4 sts=4 et filetype=sh

# Include wired net drivers, excluding wireless

net_module_test() {
    local net_drivers='eth_type_trans|register_virtio_device'
    local unwanted_drivers='/(wireless|isdn|uwb)/'
    egrep -q $net_drivers "$1" && \
        egrep -qv 'iw_handler_get_spy' "$1" && \
        [[ ! $1 =~ $unwanted_drivers ]]
}

instmods $(filter_kernel_modules net_module_test)

instmods ecb arc4
# bridge modules
instmods bridge stp llc
instmods ipv6
# bonding
instmods bonding
