#!/bin/bash
# -*- mode: shell-script; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
# ex: ts=8 sw=4 sts=4 et filetype=sh

modinfo -k $kernel dm_mod >/dev/null 2>&1 && \
    inst_hook pre-udev 30 "$moddir/dm-pre-udev.sh"

inst dmsetup

type -P dmeventd >/dev/null && dracut_install dmeventd
inst_rules 10-dm.rules 95-dm-notify.rules
