#!/bin/sh
export PATH=/sbin:/bin:/usr/sbin:/usr/bin
exec >/dev/console 2>&1
export TERM=linux
export PS1='initramfs-test:\w\$ '
stty sane
echo "made it to the rootfs! Powering down."
echo OK $(cat /dev/.run/initramfs/net.ifaces) > /dev/sda
#sh -i
poweroff -f
