#!/bin/sh
exec >/dev/console 2>&1
export TERM=linux
export PS1='initramfs-test:\w\$ '
stty sane
echo "made it to the rootfs! Powering down."
echo OK $(cat /dev/.initramfs/net.ifaces) > /dev/sda
#sh -i
poweroff -f
