FROM registry.opensuse.org/opensuse/tumbleweed-dnf:latest

MAINTAINER https://github.com/dracutdevs/dracut

# Install needed packages for the dracut CI container
RUN dnf -y install --setopt=install_weak_deps=False \
    dash asciidoc mdadm lvm2 dmraid cryptsetup nfs-utils nbd dhcp-server \
    strace libkmod-devel gcc bzip2 xz tar wget rpm-build make git bash-completion \
    kernel dhcp-client qemu-kvm /usr/bin/qemu-system-$(uname -m) e2fsprogs \
    tcpdump iproute iputils kbd NetworkManager btrfsprogs tgt dbus-broker \
    iscsiuio open-iscsi which ShellCheck shfmt procps pigz parted squashfs ntfsprogs \
    multipath-tools util-linux-systemd systemd-boot \
    && dnf -y remove dracut && dnf -y update && dnf clean all
