FROM docker.io/archlinux

MAINTAINER https://github.com/dracutdevs/dracut

ENV container docker
LABEL RUN="docker run -it --name NAME --privileged --ipc=host --net=host --pid=host -e NAME=NAME -e IMAGE=IMAGE IMAGE"

RUN echo 'export DRACUT_NO_XATTR=1 KVERSION=$(cd /lib/modules; ls -1 | tail -1)' > /etc/profile.d/dracut-test.sh

# Install needed packages for the dracut CI container
RUN pacman --noconfirm -Syu \
    linux dash strace dhclient asciidoc cpio pigz squashfs-tools \
    qemu btrfs-progs mdadm dmraid nfs-utils nfsidmap lvm2 nbd \
    dhcp networkmanager multipath-tools vi tcpdump open-iscsi connman \
    git shfmt shellcheck astyle which base-devel glibc parted ntfs-3g && yes | pacman -Scc

RUN useradd -m build
RUN su build -c 'cd && git clone https://aur.archlinux.org/perl-config-general.git && cd perl-config-general && makepkg -s --noconfirm'
RUN pacman -U --noconfirm ~build/perl-config-general/*.pkg.tar.*
RUN su build -c 'cd && git clone https://aur.archlinux.org/tgt.git && cd tgt && makepkg -s --noconfirm'
RUN pacman -U --noconfirm ~build/tgt/*.pkg.tar.*
RUN rm -fr ~build

# Set default command
CMD ["/usr/bin/bash"]
