FROM docker.io/gentoo/portage:latest as portage

# uefi stub in a separate builder
FROM docker.io/gentoo/stage3 as efistub
COPY --from=portage /var/db/repos/gentoo /var/db/repos/gentoo

# systemd-boot
RUN mkdir -p /etc/portage/package.accept_keywords && \
    echo "sys-boot/systemd-boot" >> /etc/portage/package.accept_keywords/systemd-boot && \
    echo '>=sys-apps/systemd-utils-251.10 boot' > /etc/portage/package.use/systemd-boot && \
    emerge -qv sys-boot/systemd-boot

# kernel and its dependencies in a separate builder
FROM docker.io/gentoo/stage3:musl as kernel
COPY --from=portage /var/db/repos/gentoo /var/db/repos/gentoo
RUN emerge -qv sys-kernel/gentoo-kernel-bin

FROM docker.io/gentoo/stage3:musl
COPY --from=portage /var/db/repos/gentoo /var/db/repos/gentoo
COPY --from=kernel /boot /boot
COPY --from=kernel /lib/modules /lib/modules
COPY --from=efistub /usr/lib/systemd/boot/efi /usr/lib/systemd/boot/efi

MAINTAINER https://github.com/dracutdevs/dracut

# Only install `dmsetup`: attempting to install all of lvm2 fails due to missing kernel headers.
RUN echo 'sys-fs/lvm2 device-mapper-only -thin' > /etc/portage/package.use/lvm2

# workaround for https://bugs.gentoo.org/734022 whereby Gentoo does not support NFS4 with musl
RUN echo 'net-fs/nfs-utils -nfsv4' > /etc/portage/package.use/nfs-utils

RUN echo '>=sys-fs/lvm2-2.03.17-r1 lvm' > /etc/portage/package.use/dmraid

# Install needed packages for the dracut CI container
RUN emerge -qv \
    app-arch/cpio \
    app-emulation/qemu \
    app-shells/dash \
    net-fs/nfs-utils \
    net-misc/dhcp \
    sys-apps/busybox \
    sys-block/nbd \
    sys-block/open-iscsi \
    sys-block/parted \
    sys-block/thin-provisioning-tools \
    sys-fs/btrfs-progs \
    sys-fs/cryptsetup \
    sys-fs/dmraid \
    sys-fs/lvm2 \
    sys-fs/mdadm \
    sys-fs/multipath-tools \
    sys-fs/ntfs3g \
    sys-fs/squashfs-tools \
    && rm -rf /var/cache/* /usr/share/doc/* /usr/share/man/*
