FROM docker.io/debian:latest

MAINTAINER https://github.com/dracutdevs/dracut

COPY tools/* /tmp/
WORKDIR /tmp

# Install needed packages for the dracut CI container
# Install dracut as a linux-initramfs-tool provider so that the default initramfs-tool package does not get installed
# Uninstall initramfs-tools-core as a workaround for https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=994492
RUN apt-get update -y -qq && apt-get upgrade -y -qq && apt-get install -y -qq --no-install-recommends dracut && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends -o Dpkg::Use-Pty=0 $(/tmp/test-packages.sh) \
    && apt-get clean && dpkg -P --force-depends dracut dracut-core initramfs-tools-core
