FROM registry.opensuse.org/opensuse/tumbleweed-dnf:latest

MAINTAINER https://github.com/dracutdevs/dracut

COPY tools/* /tmp/
WORKDIR /tmp

# Install needed packages for the dracut CI container
RUN dnf -y install --setopt=install_weak_deps=False $(/tmp/test-packages.sh) \
    && dnf -y remove dracut && dnf -y update && dnf clean all
