FROM registry.fedoraproject.org/fedora:latest

MAINTAINER https://github.com/dracutdevs/dracut

ENV container docker
LABEL RUN="docker run -it --name NAME --privileged --ipc=host --net=host --pid=host -e NAME=NAME -e IMAGE=IMAGE IMAGE"

RUN echo 'export DRACUT_NO_XATTR=1 KVERSION=$(cd /lib/modules; ls -1 | tail -1)' > /etc/profile.d/dracut-test.sh

# Install needed packages for the dracut CI container
RUN dnf -y install --setopt=install_weak_deps=False \
    asciidoc \
    bash-completion \
    btrfs-progs \
    bzip2 \
    cryptsetup \
    dash \
    dbus-daemon \
    dhcp-client \
    dhcp-server \
    dmraid \
    e2fsprogs \
    gcc \
    git \
    iproute \
    iputils \
    iscsi-initiator-utils \
    kbd \
    kernel \
    kmod-devel \
    lvm2 \
    make \
    mdadm \
    nbd \
    NetworkManager \
    nfs-utils \
    ntfsprogs \
    parted \
    pigz \
    qemu-system-x86-core \
    rpm-build \
    scsi-target-utils \
    ShellCheck \
    shfmt \
    squashfs-tools \
    strace \
    sudo \
    systemd-networkd \
    tar \
    tcpdump \
    wget \
    which \
    xz \
    && dnf -y remove dracut --noautoremove && dnf -y update && dnf clean all

# Set default command
CMD ["/usr/bin/bash"]
