#!/bin/bash
# FIXME: would be nice if we didn't have to know which rules to grab....
# ultimately, /lib/initramfs/rules.d or somesuch which includes links/copies
# of the rules we want so that we just copy those in would be best
dracut_install udevd udevadm /lib*/udev/*_id /etc/udev/udev.conf /etc/group
dracut_install basename
inst_rules 50-udev-default.rules 60-persistent-storage.rules \
    61-persistent-storage-edd.rules 80-drivers.rules 95-udev-late.rules 
#Some debian udev rules are named differently
inst_rules 50-udev.rules 95-late.rules
 
if ldd $(find_binary udevd) |grep -q /lib64/libc; then
    dracut_install /lib64/libnss_files*
else
    dracut_install /lib/libnss_files*
fi
