#!/bin/bash
if ldd /proc/$$/exe |grep -q lib64; then
    LIBDIR="/usr/lib64"
else
    LIBDIR="/usr/lib"
fi
PLYMOUTH_LOGO_FILE="/usr/share/pixmaps/system-logo-white.png"
PLYMOUTH_PLUGIN_NAME=$(plymouth-set-default-theme)

inst /sbin/plymouthd /bin/plymouthd
dracut_install /bin/plymouth "${LIBDIR}/plymouth/text.so" \
    "/usr/share/plymouth/themes/details/details.plymouth" \
    "${LIBDIR}/plymouth/details.so" "${PLYMOUTH_LOGO_FILE}" \
    /etc/system-release 

if [[ -f "${LIBDIR}/plymouth/${PLYMOUTH_PLUGIN_NAME:=text}.so" ]]; then
    dracut_install "${LIBDIR}/plymouth/${PLYMOUTH_PLUGIN_NAME:=text}.so" 
fi

mkdir -p "${initdir}/usr/share/plymouth"

[[ -f ${LIBDIR}/plymouth/default.so ]] && inst ${LIBDIR}/plymouth/default.so

if [[ -d /usr/share/plymouth/themes/${PLYMOUTH_PLUGIN_NAME} ]]; then
    for x in "/usr/share/plymouth/themes/${PLYMOUTH_PLUGIN_NAME}"/* ; do
        [[ -f "$x" ]] || break
        inst $x
    done
fi

if [ -L /usr/share/plymouth/themes/default.plymouth ]; then
    inst /usr/share/plymouth/themes/default.plymouth
fi

# vim:ts=8:sw=4:sts=4:et
