#!/bin/bash
if ldd /sbin/plymouthd |grep -q lib64; then
    LIBDIR="/usr/lib64"
else
    LIBDIR="/usr/lib"
fi
PLYMOUTH_LOGO_FILE="/usr/share/pixmaps/system-logo-white.png"
PLYMOUTH_THEME=$(plymouth-set-default-theme)

inst /sbin/plymouthd /bin/plymouthd
dracut_install /bin/plymouth \
    "${PLYMOUTH_LOGO_FILE}" \
    /etc/system-release 

mkdir -p "${initdir}/usr/share/plymouth"

if [[ $hostonly ]]; then 
    dracut_install "${LIBDIR}/plymouth/text.so" \
	"${LIBDIR}/plymouth/details.so" \
	"/usr/share/plymouth/themes/details/details.plymouth" \
	"/usr/share/plymouth/themes/text/text.plymouth" \

    if [[ -d /usr/share/plymouth/themes/${PLYMOUTH_THEME} ]]; then
	for x in "/usr/share/plymouth/themes/${PLYMOUTH_THEME}"/* ; do
            [[ -f "$x" ]] || break
            inst $x
	done
    fi

    if [ -L /usr/share/plymouth/themes/default.plymouth ]; then
	inst /usr/share/plymouth/themes/default.plymouth
        # Install plugin for this theme
	PLYMOUTH_PLUGIN=$(grep "^ModuleName=" /usr/share/plymouth/themes/default.plymouth | while read a b c; do echo $b; done;)
	inst ${LIBDIR}/plymouth/${PLYMOUTH_PLUGIN}.so
    fi
else
    for x in /usr/share/plymouth/themes/{text,details}/* ; do
        [[ -f "$x" ]] || continue
	THEME_DIR=$(dirname "$x")
	mkdir -p "${initdir}/$THEME_DIR"
        dracut_install "$x"
    done
    for x in ${LIBDIR}/plymouth/{text,details}.so ; do
        [[ -f "$x" ]] || continue
        [[ "$x" != "${x%%/label.so}" ]] && continue
        dracut_install "$x"
    done
    (
	cd ${initdir}/usr/share/plymouth/themes;
	ln -s text/text.plymouth default.plymouth 2>&1;       
    )
fi

# vim:ts=8:sw=4:sts=4:et
