#!/bin/bash
inst lvm

inst_rules "$moddir/64-lvm.rules" 64-lvm.rules

if [[ $hostonly ]] || [[ $lvmconf = "yes" ]]; then 
    if [ -f /etc/lvm/lvm.conf ]; then
	inst /etc/lvm/lvm.conf
	# FIXME: near-term hack to establish read-only locking;
	# use command-line lvm.conf editor once it is available
	sed -i -e 's/\(^[[:space:]]*\)locking_type[[:space:]]*=[[:space:]]*[[:digit:]]/\1locking_type = 4/' ${initdir}/etc/lvm/lvm.conf
    fi
fi

inst_rules 10-dm.rules 13-dm-disk.rules 95-dm-notify.rules 11-dm-lvm.rules

inst "$moddir/lvm_scan.sh" /sbin/lvm_scan
inst_hook cmdline 30 "$moddir/parse-lvm.sh"
