#!/bin/bash
inst lvm
if [ -x /lib/udev/vol_id ]; then
    inst_rules "$moddir/64-lvm-vol_id.rules" 64-device-mapper.rules
else
    inst_rules "$moddir/64-lvm.rules" 64-device-mapper.rules
fi

if [[ $hostonly ]]; then 
    [ -f /etc/lvm/lvm.conf ] && inst /etc/lvm/lvm.conf
fi

inst "$moddir/lvm_scan.sh" /sbin/lvm_scan
inst_hook cmdline 30 "$moddir/parse-lvm.sh"
inst_hook pre-pivot 30 "$moddir/lvm-cleanup.sh"
inst_hook pre-pivot 31 "$moddir/lvm-cleanup.sh"