#!/bin/bash

inst /sbin/bootchartd 
inst /bin/bash 
ln -s /init "${initdir}/sbin/init"
mkdir -p /lib/bootchart/
inst /lib/bootchart/bootchart-collector 
inst /etc/bootchartd.conf 
inst /sbin/accton 
inst /usr/bin/pkill /bin/pkill
inst /bin/echo
inst /bin/grep 
inst /bin/usleep
inst /usr/bin/[  /bin/[
mknod -m 0666 "${initdir}/dev/null" c 1 3
