#!/bin/bash

# No Xen-detect? Boo!!
which xen-detect >/dev/null 2>&1 || exit 1

. $dracutfunctions
[[ $debug ]] && set -x

# Yes, we are under Xen PV env.
xen-detect | egrep -q -v 'PV' || exit 0

exit 1
