#!/bin/bash

# No Xen-detect? Boo!!
if ! hash xen-detect 2>/dev/null; then
    [[ -d /usr/lib/xen-default ]] && \
        hash -p /usr/lib/xen-default/bin/xen-detect xen-detect || exit 1
fi

. $dracutfunctions
[[ $debug ]] && set -x

# Yes, we are under Xen PV env.
xen-detect | grep -q -v PV || exit 0

exit 1
