#!/bin/bash
# -*- mode: shell-script; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
# ex: ts=8 sw=4 sts=4 et filetype=sh

for i in \
    xenbus_probe_frontend xen-pcifront \
    xen-fbfront xen-kbdfront xen-blkfront xen-netfront \
    ; do
    modinfo -k $kernel $i >/dev/null 2>&1 && instmods $i
done

