#!/bin/sh
# We depend on network modules being loaded
[ "$1" = "-d" ] && echo network

# If hostonly was requested, fail the check if we are not actually
# booting from root.
#[ "$1" = "-h" ] && ! egrep -q '/ /dev/nbd[0-9]*' /proc/mounts && exit 1

# If our prerequisites are not met, fail anyways.
which iscsistart hostname >/dev/null 2>&1 || exit 1
exit 0
