#!/bin/sh
[ "$1" = "-d" ] && echo network
[ "$1" = "-H" ] || [ "$1" = "--hostonly" ] && ! egrep -q '/ nfs[34 ]' /proc/mounts && exit 1
which rpcbind rpc.statd mount.nfs mount.nfs4 umount >/dev/null 2>&1 || exit 1
exit 0
