#!/bin/bash
# -*- mode: shell-script; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
# ex: ts=8 sw=4 sts=4 et filetype=sh
inst nbd-client
inst_hook cmdline 90 "$moddir/parse-nbdroot.sh"

inst "$moddir/nbdroot" "/sbin/nbdroot"
