#!/bin/bash
# udev rules for ubuntu 8.10
# content from /usr/share/initramfs-tools/hooks/udev
mkdir -p "$initdir/etc/udev/rules.d"
mkdir -p "$initdir/var/run"

dracut_install udevd udevadm pkill
dracut_install /etc/udev/udev.conf

for rules in 05-options.rules 20-names.rules 40-basic-permissions.rules 60-persistent-storage.rules 61-persistent-s
    dracut_install /etc/udev/rules.d/$rules 
done

dracut_install /lib/udev/dvb_device_name 
dracut_install /lib/udev/usb_device_name 
dracut_install /lib/udev/ata_id 
dracut_install /lib/udev/usb_id 
dracut_install /lib/udev/vol_id 
dracut_install /lib/udev/scsi_id 
dracut_install /lib/udev/path_id 
dracut_install /lib/udev/edd_id 
dracut_install /lib/udev/firmware_helper 
dracut_install /lib/udev/ide_media 
dracut_install /lib/udev/vio_type 
dracut_install /lib/udev/watershed 
