#!/bin/bash

# No mdadm?  No mdraid support.
type -P mdadm >/dev/null || exit 1

. $dracutfunctions
[[ $debug ]] && set -x

is_mdraid() { [[ -d "/sys/dev/block/$1/md" ]]; }

[[ $1 = '-h' ]] && {
    rootdev=$(find_root_block_device)
    if [[ $rootdev ]]; then
	# root lives on a block device, so we can be more precise about 
	# hostonly checking
	check_block_and_slaves is_mdraid "$rootdev" || exit 1
    else
	# root is not on a block device, use the shotgun approach
	blkid | egrep -q '(linux|isw)_raid' || exit 1
    fi
}

exit 0
