#!/bin/bash
dracut_install mdadm
# XXX: mdmon really needs to run as non-root?
#      If so, write only the user it needs in the initrd's /etc/passwd (and maybe /etc/group)
#      in a similar fashion to modules.d/95nfs.  Do not copy /etc/passwd and /etc/group from 
#      the system into the initrd.
#      dledford has hardware to test this, so he should be able to clean this up.
inst /etc/passwd
inst /etc/group
instmods =drivers/md

if [ -x /lib/udev/vol_id ]; then
    inst_rules "$moddir/61-mdadm.rules"
else
    inst_rules "$moddir/65-md-incremental.rules"
    inst_rules 64-md-raid.rules
fi

[ -f /etc/mdadm/mdadm.conf ] && inst /etc/mdadm/mdadm.conf /etc/mdadm.conf
[ -f /etc/mdadm.conf ] && inst /etc/mdadm.conf
if [ -x  /sbin/mdmon ] ; then
    dracut_install mdmon
    inst_hook pre-pivot 30 "$moddir/mdmon-pre-pivot.sh"
fi 

inst "$moddir/mdraid_start.sh" /sbin/mdraid_start

