#!/bin/bash
# -*- mode: shell-script; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
# ex: ts=8 sw=4 sts=4 et filetype=sh

inst_hook cmdline 30 "$moddir/parse-ccw.sh"
inst /lib/udev/ccw_init
inst_rules 81-ccw.rules
dracut_install znet_cio_free grep sed seq readlink
