#!/bin/bash
inst_hook cmdline 30 "$moddir/parse-ccw.sh"
inst /lib/udev/ccw_init
#inst_rules 55-ccw.rules || inst_rules "$moddir/55-ccw.rules"
inst_rules 81-ccw.rules
dracut_install znet_cio_free grep sed seq readlink
