#!/bin/bash
for bin in /usr/sbin/resume /usr/lib/suspend/resume
do
    [ -x "${bin}" ] && break 
done

inst "${bin}" /usr/sbin/resume
[ -f /etc/suspend.conf ] && inst /etc/suspend.conf

inst_hook cmdline 10 "$moddir/parse-uswsusp.sh"
inst_hook mount 10 "$moddir/resume-uswsusp.sh"
