#!/bin/bash
# -*- mode: shell-script; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
# ex: ts=8 sw=4 sts=4 et filetype=sh

for bin in /usr/sbin/resume /usr/lib/suspend/resume
do
    [ -x "${bin}" ] && break 
done

inst "${bin}" /usr/sbin/resume
[ -f /etc/suspend.conf ] && inst /etc/suspend.conf

inst_hook cmdline 10 "$moddir/parse-uswsusp.sh"
inst_hook mount 10 "$moddir/resume-uswsusp.sh"
