#!/bin/bash
# terminfo bits make things work better if you fall into interactive mode
TERMINFODIR="/lib/terminfo"

[ ! -d ${TERMINFODIR} -a -d "/etc/terminfo" ] && \
	TERMINFODIR="/etc/terminfo"

dracut_install $(find ${TERMINFODIR} -type f)
