#!/bin/bash
# terminfo bits make things work better if you fall into interactive mode
for TERMINFODIR in /lib/terminfo /etc/terminfo /usr/share/terminfo; do
	[ -d ${TERMINFODIR} ] && break
done

[ -d ${TERMINFODIR} ] && \
	dracut_install $(find ${TERMINFODIR} -type f)
