#!/bin/sh

. /lib/dracut-lib.sh

while [ $# -gt 0 ]; do
    case "$1" in
	--onetime)
	    onetime="yes";;
	--settled)
	    settled="-settled";;
	--unique)
	    unique="yes";;
	--name)
	    name="$2";shift;;
	*)
	    break;;
    esac
    shift
done

if [ -z "$unique" ]; then
	job="${name}$$"
else
	job="${name:-$1}"
	job=${job##*/}
fi

echo "$@" > "/tmp/${job}.sh"
if [ -n "$onetime" ]; then
   echo '[ -e "$job" ] && rm "$job"' >> "/tmp/${job}.sh"
fi
mv -f "/tmp/${job}.sh" /initqueue${settled}/
[ -z "$settled" ] && >> /initqueue/work
