#!/bin/bash
dracut_install mount mknod mkdir modprobe pidof sleep chroot echo sed bash ls flock 
[ -e "${initdir}/bin/sh" ] || (ln -s bash "${initdir}/bin/sh" || :)
# install our scripts and hooks
inst "$moddir/init" "/init"
inst "$moddir/switch_root" "/sbin/switch_root"
inst_hook pre-pivot 50 "$moddir/selinux-loadpolicy.sh"
