#!/bin/bash
dracut_install mount mknod mkdir pidof sleep chroot sed ls flock cp mv dmesg \
        rm ln mkfifo less 
if [[ ${ignore_kmodules} = yes ]]; then
    inst /bin/true
    ln -s /bin/true "${initdir}"/sbin/modprobe
    ln -s /bin/true "${initdir}"/sbin/rmmod
else
    dracut_install modprobe rmmod
fi
if [ ! -e "${initdir}/bin/sh" ]; then
    dracut_install bash
    (ln -s bash "${initdir}/bin/sh" || :)
fi
# install our scripts and hooks
inst "$moddir/init" "/init"
inst "$moddir/initqueue" "/sbin/initqueue"
inst "$moddir/loginit" "/sbin/loginit"
mkdir -p ${initdir}/initqueue
mkdir -p ${initdir}/initqueue-finished
mkdir -p ${initdir}/initqueue-settled
mkdir -p ${initdir}/tmp
# Bail out if switch_root does not exist
if type -P switch_root >/dev/null; then
    dracut_install switch_root 
else
    inst "$moddir/switch_root" "/sbin/switch_root" \
            || derror "Failed to install switch_root"
fi
inst "$moddir/dracut-lib.sh" "/lib/dracut-lib.sh"
inst_hook cmdline 10 "$moddir/parse-root-opts.sh"
inst_hook cmdline 20 "$moddir/parse-blacklist.sh"
mkdir -p "${initdir}/var/run"
