#!/bin/bash
# -*- mode: shell-script; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
# ex: ts=8 sw=4 sts=4 et filetype=sh

# if cryptsetup is not installed, then we cannot support encrypted devices.
type -P cryptsetup >/dev/null || exit 1

[ "$1" = "-d" ] && echo dm

. $dracutfunctions

is_crypt() { [[ $(get_fs_type /dev/block/$1) = crypto_LUKS ]]; }

[[ $1 = '-h' ]] && {
    rootdev=$(find_root_block_device)
    if [[ $rootdev ]]; then
        # root lives on a block device, so we can be more precise about 
        # hostonly checking
        check_block_and_slaves is_crypt "$rootdev" || exit 1
    else
        # root is not on a block device, use the shotgun approach
        blkid | grep -q crypto\?_LUKS || exit 1
    fi
}

exit 0
