## The test container is created with https://github.com/dracutdevs/fedora-container

name: Fedora

on:
    pull_request:
        branches: [ master ]

jobs:
    test:
        runs-on: ubuntu-latest
        timeout-minutes: 45
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.fedora }}-${{ matrix.test }}
            cancel-in-progress: true
        strategy:
            matrix:
                fedora: [
                        "32", "33", "34", "latest"
                ]
                test: [
                        "01",
                        "02",
                        "03",
                        "04",
                        "10",
                        "11",
                        "12",
                        "13",
                        "14",
                        "15",
                        "17",
                        "20",
                        "21",
                        "30",
                        "31",
                        "35",
                        "36",
                        "40",
                        "41",
                        "98",
                ]
            fail-fast: false
        container:
            image: quay.io/haraldh/dracut-fedora:${{ matrix.fedora }}
            options: "-v /dev/kvm:/dev/kvm"
        steps:
            -   name: "Checkout Repository"
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0

            -   name: "F${{ matrix.fedora }} TEST-${{ matrix.test }} ${{ github.head_ref }}"
                run: ./fedora-test-github.sh "TEST-${{ matrix.test }}" ${{ matrix.test }}
