#!/bin/bash

inst_hook pre-trigger 01 "$moddir/fips.sh"
dracut_install sha512hmac rmmod insmod mount uname umount

for dir in "$usrlibdir" "$libdir"; do
    [[ -e $dir/libsoftokn3.so ]] && \
        dracut_install $dir/libsoftokn3.so $dir/libsoftokn3.chk \
            $dir/libfreebl3.so $dir/libfreebl3.chk && \
                break
done

dracut_install $usrlibdir/hmaccalc/sha512hmac.hmac

# vim:ts=8:sw=4:sts=4:et
